### PR TITLE
Fix composer issue, update to PHP 7.3, various tweaks

### LINKED ISSUE #19: Update PHP to 7.3
7.2 is outdated. We could also allow the user to select which version of PHP to install (7.3 or 7.4)?

### LINKED ISSUE #21: Add n98-magerun2
This is super helpful for clearing generated, etc.

### LINKED ISSUE #24: .bash_profile updates
Could we add this to the `.bashrc` or a new `.bash_profile`?

```
# use colors in terminal
export PS1="\[\033[36m\]\u\[\033[m\]@\[\033[32m\]\h:\[\033[33;1m\]\w\[\033[m\]\$ "

alias m2="cd /var/www/html/shared/magento2ce"
```

### LINKED ISSUE #25: Your requirements could not be resolved to an installable set of packages.
Hi! Running docker-compose -f docker-compose_windows.yml up -d gives the following on step 3:

[...]
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires magento/product-community-edition 2.3.4 -> satisfiable by magento/product-community-edition[2.3.4].
    - magento/product-community-edition 2.3.4 requires magento/composer ~1.5.0 -> satisfiable by magento/composer[1.5.0, 1.5.1] from composer repo (https://repo.packagist.org) but magento/composer[1.0.2, ..., 1.6.0] from composer repo (https://repo.magento.com) has higher repository priority. The packages with higher priority do not match your constraint and are therefore not installable. See https://getcomposer.org/repoprio for details and assistance.
  Problem 2
    - Root composer.json requires dealerdirect/phpcodesniffer-composer-installer ^0.5.0 -> satisfiable by dealerdirect/phpcodesniffer-composer-installer[v0.5.0].
    - dealerdirect/phpcodesniffer-composer-installer v0.5.0 requires composer-plugin-api ^1.0 -> found composer-plugin-api[2.0.0] but it does not match the constraint.

You are using Composer 2, which some of your plugins seem to be incompatible with. Make sure you update your plugins or report a plugin-issue to ask them to support Composer 2.
Service 'm23' failed to build : The command '/bin/sh -c composer create-project --repository=https://repo.magento.com/ magento/project-community-edition=2.3.4 /var/www/html/magento2ce/' returned a non-zero code: 2

### LINKED ISSUE #26: composer 2 breaks installation
Some dependencies require composer v1  but the Dockerfile installs the latest version - which since a few days now - is 2.

### LINKED ISSUE #28: Add crontab
```
crontab -e

bash: crontab: command not found
```

### PR DESCRIPTION
**Pull request by lfolco**
Fixes #25, Fixes #26, Fixes #28, Fixes #24, Fixes #19, Fixes #21

### CODE REVIEW

**Comment by lfolco** [comment]
> I read, you can user self-update -1 and it uses the latest 1.x

Updated. thanks!

**Comment by cicerorfonseca** [comment]
When is that supposed to be merged? I'm having all kinds of issues installing Magento and I think these changes will solve most of the problems.

**Comment by lfolco** [comment]
@cicerorfonseca try using my repo instead, see if that fixes your errors: https://github.com/lfolco/magento2-dk

**Comment by cicerorfonseca** [comment]
it worked perfectly on your repo @lfolco, thanks!

**Pull request merged**
